/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Parkplatz {
  'id' : bigint,
  'situationsbild' : [] | [ExternalBlob],
  'host' : Principal,
  'verfuegbarkeit' : Array<Verfuegbarkeit>,
  'adresse' : string,
  'maxParkdauer' : bigint,
  'qrCodeUrl' : string,
  'preis' : bigint,
  'beschreibung' : string,
  'wochentageVerfuegbarkeit' : Array<WochentagVerfuegbarkeit>,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Reservierung {
  'id' : bigint,
  'status' : ReservierungsStatus,
  'startZeit' : bigint,
  'endZeit' : bigint,
  'gast' : Principal,
  'parkplatzId' : bigint,
  'istQrCodeReservierung' : boolean,
  'zahlungsId' : [] | [string],
  'bezahlt' : boolean,
  'kennzeichen' : [] | [string],
  'fahrzeugmarke' : [] | [string],
}
export interface ReservierungMitName {
  'id' : bigint,
  'status' : ReservierungsStatus,
  'startZeit' : bigint,
  'endZeit' : bigint,
  'gast' : Principal,
  'name' : string,
  'parkplatzId' : bigint,
  'istQrCodeReservierung' : boolean,
  'zahlungsId' : [] | [string],
  'bezahlt' : boolean,
  'kennzeichen' : [] | [string],
  'fahrzeugmarke' : [] | [string],
}
export type ReservierungsStatus = { 'eingecheckt' : null } |
  { 'ausgecheckt' : null } |
  { 'reserviert' : null } |
  { 'storniert' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'active' : boolean,
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Verfuegbarkeit { 'istVerfuegbar' : boolean, 'datum' : bigint }
export interface WochentagVerfuegbarkeit {
  'startZeit' : bigint,
  'endZeit' : bigint,
  'wochentag' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'alleBenutzer' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'alleParkplaetze' : ActorMethod<[], Array<Parkplatz>>,
  'alleReservierungen' : ActorMethod<[], Array<ReservierungMitName>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'benutzerDeaktivieren' : ActorMethod<[Principal], undefined>,
  'checkIn' : ActorMethod<[bigint], undefined>,
  'checkOut' : ActorMethod<[bigint], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentTime' : ActorMethod<[], bigint>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getStripeConfiguration' : ActorMethod<[], [] | [StripeConfiguration]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markReservationAsPaid' : ActorMethod<[bigint, string], undefined>,
  'meineReservierungen' : ActorMethod<[], Array<Reservierung>>,
  'parkplatzAnlegen' : ActorMethod<
    [
      string,
      string,
      bigint,
      [] | [ExternalBlob],
      bigint,
      Array<WochentagVerfuegbarkeit>,
    ],
    bigint
  >,
  'parkplatzBearbeiten' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      [] | [ExternalBlob],
      bigint,
      Array<WochentagVerfuegbarkeit>,
    ],
    undefined
  >,
  'parkplatzLoeschen' : ActorMethod<[bigint], undefined>,
  'qrCheckinOrCheckout' : ActorMethod<
    [bigint, [] | [string], [] | [string]],
    string
  >,
  'registerWithInvite' : ActorMethod<[string, string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'reservierungAnlegen' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'reservierungenFuerHost' : ActorMethod<[], Array<ReservierungMitName>>,
  'rolleZuweisen' : ActorMethod<[Principal, UserRole], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateReservierungZahlungsstatus' : ActorMethod<[bigint, string], undefined>,
  'validateInviteCode' : ActorMethod<[string], boolean>,
  'verfuegbareParkplaetze' : ActorMethod<[bigint], Array<Parkplatz>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];