/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Verfuegbarkeit = IDL.Record({
  'istVerfuegbar' : IDL.Bool,
  'datum' : IDL.Int,
});
export const WochentagVerfuegbarkeit = IDL.Record({
  'startZeit' : IDL.Nat,
  'endZeit' : IDL.Nat,
  'wochentag' : IDL.Nat,
});
export const Parkplatz = IDL.Record({
  'id' : IDL.Nat,
  'situationsbild' : IDL.Opt(ExternalBlob),
  'host' : IDL.Principal,
  'verfuegbarkeit' : IDL.Vec(Verfuegbarkeit),
  'adresse' : IDL.Text,
  'maxParkdauer' : IDL.Nat,
  'qrCodeUrl' : IDL.Text,
  'preis' : IDL.Nat,
  'beschreibung' : IDL.Text,
  'wochentageVerfuegbarkeit' : IDL.Vec(WochentagVerfuegbarkeit),
});
export const ReservierungsStatus = IDL.Variant({
  'eingecheckt' : IDL.Null,
  'ausgecheckt' : IDL.Null,
  'reserviert' : IDL.Null,
  'storniert' : IDL.Null,
});
export const ReservierungMitName = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReservierungsStatus,
  'startZeit' : IDL.Int,
  'endZeit' : IDL.Int,
  'gast' : IDL.Principal,
  'name' : IDL.Text,
  'parkplatzId' : IDL.Nat,
  'istQrCodeReservierung' : IDL.Bool,
  'zahlungsId' : IDL.Opt(IDL.Text),
  'bezahlt' : IDL.Bool,
  'kennzeichen' : IDL.Opt(IDL.Text),
  'fahrzeugmarke' : IDL.Opt(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const Reservierung = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReservierungsStatus,
  'startZeit' : IDL.Int,
  'endZeit' : IDL.Int,
  'gast' : IDL.Principal,
  'parkplatzId' : IDL.Nat,
  'istQrCodeReservierung' : IDL.Bool,
  'zahlungsId' : IDL.Opt(IDL.Text),
  'bezahlt' : IDL.Bool,
  'kennzeichen' : IDL.Opt(IDL.Text),
  'fahrzeugmarke' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'alleBenutzer' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'alleParkplaetze' : IDL.Func([], [IDL.Vec(Parkplatz)], ['query']),
  'alleReservierungen' : IDL.Func(
      [],
      [IDL.Vec(ReservierungMitName)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'benutzerDeaktivieren' : IDL.Func([IDL.Principal], [], []),
  'checkIn' : IDL.Func([IDL.Nat], [], []),
  'checkOut' : IDL.Func([IDL.Nat], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getStripeConfiguration' : IDL.Func(
      [],
      [IDL.Opt(StripeConfiguration)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markReservationAsPaid' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'meineReservierungen' : IDL.Func([], [IDL.Vec(Reservierung)], ['query']),
  'parkplatzAnlegen' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(ExternalBlob),
        IDL.Nat,
        IDL.Vec(WochentagVerfuegbarkeit),
      ],
      [IDL.Nat],
      [],
    ),
  'parkplatzBearbeiten' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(ExternalBlob),
        IDL.Nat,
        IDL.Vec(WochentagVerfuegbarkeit),
      ],
      [],
      [],
    ),
  'parkplatzLoeschen' : IDL.Func([IDL.Nat], [], []),
  'qrCheckinOrCheckout' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'registerWithInvite' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'reservierungAnlegen' : IDL.Func([IDL.Nat, IDL.Int, IDL.Int], [IDL.Nat], []),
  'reservierungenFuerHost' : IDL.Func(
      [],
      [IDL.Vec(ReservierungMitName)],
      ['query'],
    ),
  'rolleZuweisen' : IDL.Func([IDL.Principal, UserRole], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateReservierungZahlungsstatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verfuegbareParkplaetze' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(Parkplatz)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Verfuegbarkeit = IDL.Record({
    'istVerfuegbar' : IDL.Bool,
    'datum' : IDL.Int,
  });
  const WochentagVerfuegbarkeit = IDL.Record({
    'startZeit' : IDL.Nat,
    'endZeit' : IDL.Nat,
    'wochentag' : IDL.Nat,
  });
  const Parkplatz = IDL.Record({
    'id' : IDL.Nat,
    'situationsbild' : IDL.Opt(ExternalBlob),
    'host' : IDL.Principal,
    'verfuegbarkeit' : IDL.Vec(Verfuegbarkeit),
    'adresse' : IDL.Text,
    'maxParkdauer' : IDL.Nat,
    'qrCodeUrl' : IDL.Text,
    'preis' : IDL.Nat,
    'beschreibung' : IDL.Text,
    'wochentageVerfuegbarkeit' : IDL.Vec(WochentagVerfuegbarkeit),
  });
  const ReservierungsStatus = IDL.Variant({
    'eingecheckt' : IDL.Null,
    'ausgecheckt' : IDL.Null,
    'reserviert' : IDL.Null,
    'storniert' : IDL.Null,
  });
  const ReservierungMitName = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReservierungsStatus,
    'startZeit' : IDL.Int,
    'endZeit' : IDL.Int,
    'gast' : IDL.Principal,
    'name' : IDL.Text,
    'parkplatzId' : IDL.Nat,
    'istQrCodeReservierung' : IDL.Bool,
    'zahlungsId' : IDL.Opt(IDL.Text),
    'bezahlt' : IDL.Bool,
    'kennzeichen' : IDL.Opt(IDL.Text),
    'fahrzeugmarke' : IDL.Opt(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const Reservierung = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReservierungsStatus,
    'startZeit' : IDL.Int,
    'endZeit' : IDL.Int,
    'gast' : IDL.Principal,
    'parkplatzId' : IDL.Nat,
    'istQrCodeReservierung' : IDL.Bool,
    'zahlungsId' : IDL.Opt(IDL.Text),
    'bezahlt' : IDL.Bool,
    'kennzeichen' : IDL.Opt(IDL.Text),
    'fahrzeugmarke' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'alleBenutzer' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'alleParkplaetze' : IDL.Func([], [IDL.Vec(Parkplatz)], ['query']),
    'alleReservierungen' : IDL.Func(
        [],
        [IDL.Vec(ReservierungMitName)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'benutzerDeaktivieren' : IDL.Func([IDL.Principal], [], []),
    'checkIn' : IDL.Func([IDL.Nat], [], []),
    'checkOut' : IDL.Func([IDL.Nat], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getStripeConfiguration' : IDL.Func(
        [],
        [IDL.Opt(StripeConfiguration)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markReservationAsPaid' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'meineReservierungen' : IDL.Func([], [IDL.Vec(Reservierung)], ['query']),
    'parkplatzAnlegen' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          IDL.Nat,
          IDL.Vec(WochentagVerfuegbarkeit),
        ],
        [IDL.Nat],
        [],
      ),
    'parkplatzBearbeiten' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          IDL.Nat,
          IDL.Vec(WochentagVerfuegbarkeit),
        ],
        [],
        [],
      ),
    'parkplatzLoeschen' : IDL.Func([IDL.Nat], [], []),
    'qrCheckinOrCheckout' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'registerWithInvite' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'reservierungAnlegen' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'reservierungenFuerHost' : IDL.Func(
        [],
        [IDL.Vec(ReservierungMitName)],
        ['query'],
      ),
    'rolleZuweisen' : IDL.Func([IDL.Principal, UserRole], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateReservierungZahlungsstatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verfuegbareParkplaetze' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(Parkplatz)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };